head_angle_publisher_node:
  ros__parameters:
    base_link: "base_footprint"

head_controller_node:
  ros__parameters:
    head_trajectory_topic: "/head_trajectory_controller/joint_trajectory"
    max_pan_limit: 0
    max_tilt_limit: 0
    min_pan_limit: 0
    min_tilt_limit: 0
    tilt_angle_navigating: 0