head_angle_publisher_node:
  ros__parameters:
    base_link: "base_footprint"

head_controller_node:
  ros__parameters:
    head_trajectory_topic: "/head_trajectory_controller/joint_trajectory"
    head_pan_joint_name: "head_pan_joint"
    head_tilt_joint_name: "head_tilt_joint"
    max_pan_limit: 1.74
    min_pan_limit: -3.141592
    max_tilt_limit: 0.47
    min_tilt_limit: -0.9
    tilt_angle_navigating: -0.9