head_angle_publisher_node:
  ros__parameters:
    base_link: "sobit_min/base_footprint"

head_controller_node:
  ros__parameters:
    head_trajectory_topic: "/sobit_mini/joint_trajectory_controller/joint_trajectory"
    head_pan_joint_name: "head_camera_pan_joint"
    head_tilt_joint_name: "head_camera_tilt_joint"
    max_pan_limit: 1.570
    min_pan_limit: -1.570
    max_tilt_limit: 0.872
    min_tilt_limit:  -0.523
    tilt_angle_navigating: -0.872